version: 2
orbs:
  docker-publish: circleci/docker-publish@0.1.7
jobs:
  build:
    docker:
    - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-deps
      - run:
          name: Install dependencies
          command: npx @karimsa/mono
      - save_cache:
          key: v{{ .Environment.CACHE_VERSION }}-deps
          paths:
            - ~/.npm
            - ~/.cache
      - setup_remote_docker
      - run:
          name: Linting
          command: npx @karimsa/mono run lint
      - run:
          name: Building
          command: npx @karimsa/mono run build
      - run:
          name: Run tests
          command: npx @karimsa/mono test
      - docker-publish/publish:
          image: patrol
          tag: unstable
      - run:
          name: Deploy latest
          command: |
            if test "$CIRCLE_BRANCH" = "master" && test v`cat package.json | grep version | cut -d: -f2 | cut -d\" -f2` = "`git describe --tags ${CIRCLE_SHA1}`"; then
              docker push karimsa/patrol:stable
            else
              echo "Skipping. No tag found."
            fi
